dist: bionic
language: node_js
sudo: true
node_js:
  - 10
  - 9
install:
  - cd client && npm install && cd ..
script:
  - sh tools/bazel_utils/install_bazel.sh
  - bazel test //pcml/...
  # - cd client && npm test
cache:
  directories:
    - client/node_modules

