images: ['gcr.io/clarify/debug:0.0.1']
steps:
- args: [pull, 'tensorflow/tensorflow:1.6.0']
  name: gcr.io/cloud-builders/docker
- args: [build, --cache-from, 'tensorflow/tensorflow:1.6.0', -t, 'gcr.io/clarify/debug:0.0.1',
    .]
  name: gcr.io/cloud-builders/docker
