images:
- gcr.io/clarify/pcml:1029-2331-d8ef
steps:
- args:
  - pull
  - gcr.io/clarify/pcml:1029-2314-d29c
  name: gcr.io/cloud-builders/docker
- args:
  - build
  - --cache-from
  - gcr.io/clarify/pcml:1029-2314-d29c
  - -t
  - gcr.io/clarify/pcml:1029-2331-d8ef
  - .
  name: gcr.io/cloud-builders/docker
