version: 2
jobs:
  client-build:
    working_directory: ~/pcml
    docker:
      - image: tensorflow/tensorflow:1.14.0-py3
    steps:
      - checkout
      - run:
          name: Update
          command: 'apt-get update'
      - run:
          name: Install NPM
          command: 'apt-get install nodejs npm -y'
      - run:
          name: Update npm
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "client/package-lock.json" }}
      - run:
          name: Install
          command: 'cd ~/pcml/client && npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "client/package-lock.json" }}
          paths:
            - client/node_modules
  client-tests:
    docker:
      - image: tensorflow/tensorflow:1.14.0-py3
    steps:
      - checkout
      - run:
          name: Test
          command: 'cd ~/pcml/client && npm test'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
  pcml-tests:
    docker:
      - image: tensorflow/tensorflow:1.14.0-py3
    steps:
      - checkout
      - run:
         name: Install Bazel
         command: 'sh tools/bazel_utils/alt_install_bazel.sh'
      - run:
         name: Test PCML
         command: 'cd ~/pcml && bazel test //pcml/...'
workflows:
  version: 2
  build_and_test:
    jobs:
      - pcml-tests
      #- client-build
      #- client-tests:
      #    requires:
      #      - client-build
      #    filters:
      #      branches:
      #        only: master

