version: 2
jobs:
  pcml-tests:
    machine: true
    steps:
      - checkout
      #- setup_remote_docker
      #   docker_layer_caching: true 
      - run:
         name: Build the test container locally
         command: 'python tools/environments/build.py --build_mode=local --static_image_id=test-container --container_type=workspace'
      - run:
         name: Non-authenticated tests
         command: 'docker run -it test-container /bin/bash -c "source ~/.bashrc; cd /build; sh tools/testing/test_local.sh"'
workflows:
  version: 2
  build_and_test:
    jobs:
      - pcml-tests

