version: 2
jobs:
  pcml-tests:
    machine: true
    steps:
      - checkout
      - run:
         name: Pull base runtime
         command: "docker pull gcr.io/clarify/runtime-base:v0.1.0-b5f1"
      - run:
         name: Run test_local.sh in runtime-base
         command: "bash -c 'source ~/.bashrc; git checkout ${CIRCLE_SHA1}; pip install -r dev-requirements.txt; sh tools/testing/test_local.sh'"

workflows:
  version: 2
  build_and_test:
    jobs:
      - pcml-tests

