version: 2
jobs:
  pcml-tests:
    machine: true
    steps:
      - checkout
      - run:
         name: Pull base runtime separately to separate logs
         command: "docker pull gcr.io/clarify/base-runtime:v0.1.0-b5f1"
      - run:
         name: Run test_local.sh in runtime-base
         command: "sh tools/testing/test_circle.sh"
workflows:
  version: 2
  build_and_test:
    jobs:
      - pcml-tests

