prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

tide:
  sync_period: 1m

  merge_method:
    projectclarify/pcml: squash

  queries:
  - repos:
    - projectclarify/pcml
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    - needs-rebase

presubmits:
  projectclarify/pcml:
  - name: test-presubmit
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]

postsubmits:
  projectclarify/pcml:
  - name: test-postsubmit
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]

