prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

tide:
  sync_period: 1m

  merge_method:
    projectclarify/clarify: squash

  queries:
  - repos:
    - projectclarify/clarify
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    - needs-rebase

presubmits:
  projectclarify/clarify:
  - name: test-presubmit
    always_run: true
    skip_report: false
    spec:
      containers:
      - command: ["/bin/bash", "-c"]
        args:
        - mkdir
          -p
          ~/testing
          &&
          cd
          ~/testing
          &&
          git
          clone
          https://github.com/projectclarify/clarify.git
          &&
          cd
          pcml
          &&
          git
          checkout
          ${PULL_PULL_SHA}
          &&
          pip
          install
          tensorflow==1.15.0
          --user
          &&
          pip
          install
          -r
          dev-requirements.txt
          --user
          &&
          sh
          tools/testing/test_local.sh
        image: gcr.io/clarify/runtime-base:v0.1.0-2370
        resources:
          requests:
            memory: "6Gi"
            cpu: "4"

postsubmits:
  projectclarify/clarify:
  - name: test-postsubmit
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]

