triggers:
- repos:
  - projectclarify/pcml
  only_org_members: true

welcome:
- repos:
  - pcml
  message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉.<br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to Project Clarify. :smiley:"

size:
  s: 10
  m: 30
  l: 100
  xl: 500
  xxl: 1000

lgtm:
- repos:
  - projectclarify/pcml
  review_acts_as_lgtm: true

plugins:
  projectclarify/pcml:
  - size
  - approve
  - assign
  - cla
  - dog
  - goose
  - heart
  - cat
  - help
  - hold
  - label
  - lgtm
  - verify-owners
  - owners-label
  - welcome
  - wip
  - trigger

external_plugins:
  projectclarify/pcml:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request
